### ISSUE TITLE
[Meta] Package consolidation

### ISSUE THREAD

**Issue by francocipollone** [maliput/maliput_sim#3]
### Summary

 - [x] Add colcon package support via [colcon-poetry-ros](https://github.com/UrbanMachine/colcon-poetry-ros) extension. #4 
 - [x] Add [tox](https://python-poetry.org/docs/faq/#is-tox-supported) #5
 - [x] Add linter(pylint?Flake8?) to tox test env #6
 - [x] Add static analyzer to tox test env:
     - [x] mypy #5 
 - [x] Create GH Action CI
    - [x] Build and test (we can rely on colcon)
    - [x] Run tox
